version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: elasticsearch
    environment:
      - cluster.name=telenet
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms6g -Xmx6g"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=true
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - transport.host=127.0.0.1
      - http.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    expose:
      - 9200
    networks:
      - elk
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.2
    container_name: kibana
    mem_limit: 912m
    expose:
      - 5601
    depends_on:
      - elasticsearch
    networks:
      - elk
volumes:
  esdata1:
    driver: local
networks:
  elk:
    driver: bridge
